/* N1 — Shared Tailwind CDN config (loaded after cdn.tailwindcss.com) */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e2e0fc",
        "on-tertiary-fixed": "#4f5051",
        "tertiary-dim": "#ebebeb",
        "on-primary-fixed": "#000000",
        "surface-container-low": "#111127",
        "tertiary-container": "#ebebeb",
        primary: "#ff9068",
        "on-background": "#e5e3ff",
        "surface-tint": "#ff9068",
        "primary-dim": "#ff743f",
        surface: "#0c0c1f",
        "surface-dim": "#0c0c1f",
        "on-surface": "#e5e3ff",
        "on-primary-container": "#451100",
        "on-secondary-fixed-variant": "#5a5971",
        "on-secondary": "#505066",
        tertiary: "#f9f9f9",
        "on-primary": "#591800",
        "inverse-surface": "#fcf8ff",
        "surface-variant": "#23233f",
        "surface-container-lowest": "#000000",
        "secondary-dim": "#d4d2ed",
        "on-secondary-fixed": "#3e3d53",
        "primary-container": "#ff7947",
        "on-tertiary-container": "#555757",
        "primary-fixed": "#ff7947",
        "secondary-container": "#45455b",
        "surface-bright": "#292948",
        "on-secondary-container": "#d0cee9",
        outline: "#74738b",
        "tertiary-fixed-dim": "#f0f1f1",
        "secondary-fixed-dim": "#d4d2ed",
        "on-tertiary": "#5e5f5f",
        "error-container": "#9f0519",
        secondary: "#e2e0fc",
        error: "#ff716c",
        "surface-container-high": "#1d1d37",
        "primary-fixed-dim": "#f5662f",
        "tertiary-fixed": "#ffffff",
        "on-tertiary-fixed-variant": "#6c6d6e",
        "on-error": "#490006",
        "surface-container": "#17172f",
        background: "#0c0c1f",
        "surface-container-highest": "#23233f",
        "inverse-primary": "#ab3700",
        "on-surface-variant": "#aaa8c3",
        "outline-variant": "#46465c",
        "inverse-on-surface": "#53536a",
        "on-primary-fixed-variant": "#551700",
        "on-error-container": "#ffa8a3",
        "error-dim": "#d7383b",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Plus Jakarta Sans"],
        label: ["Space Grotesk"],
        mono: ["Space Mono"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
};
